### ISSUE TITLE
Controllare se è corretto

### ISSUE THREAD

**Issue by edomora97** [edomora97/GAL-cheatsheet#2]
https://github.com/edomora97/GAL-cheatsheet/blob/master/teoria/2.quadriche.tex#L62

Non sono sicuro che per essere un cilindro iperbolico `x^TAx` debba essere semidefinita, per esempio:

`2x^2+y^2+2z^2-2xy+2yz+4x-2y=0` ha autovalori 2, 3, 0 quindi è semipositiva ma è un cilindro ellittico.

**Comment by edomora97** [comment]
Lo schema è definitivamente sbagliato, l'ho copiato dalle dispense che ci ha dato la prof e in alcuni punti è diverso da quello che ho nel quaderno e da quello che il buon senso suggerisce. In particolare la parte delle quadriche degeneri non comprende alcuni casi (per esempio rkA=2).

**Comment by mdonadoni** [comment]
Sinceramente non saprei, non avendolo fatto in questo modo non posso dare una mano 🙃

**Comment by edomora97** [comment]
![Schema per riconoscere le quadriche](https://cloud.githubusercontent.com/assets/6685454/22628228/b676443a-ebd0-11e6-82df-4c7e2b0ffa72.png)

**Comment by edomora97** [comment]
Sistemato con 6399727
